#
# @see https://docs.microsoft.com/en-us/azure/developer/java/fundamentals/java-jdk-docker-images
#
# FROM alpine:3.13 << to si nech pro nejake easy-as-pssible usecases
#FROM azul/zulu-openjdk-alpine:15.0.0-15.27.17-jre
FROM groovy:4.0-jre15

#COPY HttpServer.groovy /home/groovy
#RUN apk --update add openjdk7-jre

EXPOSE 8080:8082
#CMD ["/usr/bin/java", "-version"]
